name: danger-plugin-toolbox CI

permissions:
  actions: read
  contents: read
  pull-requests: write
  statuses: write

on:
  pull_request:
    branches: ['**']
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['22']

    steps:
      - uses: actions/checkout@v5

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install deps
        run: HUSKY=0 npm ci --quiet

      - name: Install danger-plugin-toolbox (for Danger step)
        run: npm install --no-save prod-danger-plugin-toolbox@npm:danger-plugin-toolbox@3.1.2
        if: github.event_name == 'pull_request' && matrix['node-version'] == '22'

      - name: Run linters
        run: (set -o pipefail; npm run lint |& tee lint.log);
        if: matrix['node-version'] == '22'

      - name: Run tests
        run: (set -o pipefail; npm run test:coverage |& tee test.log);

      - name: Run Danger
        run: npm run danger
        if: github.event_name == 'pull_request' && matrix['node-version'] == '22'
        env:
          GITHUB_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
