name: danger-plugin-toolbox Danger CI

on:
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install deps
        run: npm ci --quiet

      - name: Install danger-plugin-toolbox
        run: npm install -g danger-plugin-toolbox@1.29.0

      - name: Link danger-plugin-toolbox
        run: npm link danger-plugin-toolbox # Link the global version of "danger-plugin-toolbox" into the local "node_modules/"

      - name: Run Danger
        run: npm run danger
        env:
          GITHUB_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
