name: danger-plugin-toolbox (PR)

on:
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.14.2, 12.13]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install deps
        run: npm ci --quiet

      - name: Install danger-plugin-toolbox
        run: npm install -g danger-plugin-toolbox@1.30.0

      - name: Link danger-plugin-toolbox
        run: npm link danger-plugin-toolbox # Link the global version of "danger-plugin-toolbox" into the local "node_modules/"

      - name: Run linters
        run: (set -o pipefail; npm run lint |& tee lint.log);

      - name: Run tests
        run: (set -o pipefail; npm run test:coverage |& tee test.log);

      - name: Run Danger
        run: npm run danger
        env:
          GITHUB_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}

      - name: Run Spellcheck
        run: npm run spellcheck:ci

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
